<?php
/**
 * @var \LCB\PerfectAudience\Base $block
 */
?>
<!--Perfect Audience-->
<script type="text/javascript">// <![CDATA[
  (function() {
    window._pa = window._pa || {};
    var pa = document.createElement('script'); pa.type = 'text/javascript'; pa.async = true;
    pa.src = ('https:' == document.location.protocol ? 'https:' : 'http:') + "//tag.perfectaudience.com/serve/<?php echo $block->getId(); ?>.js";
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(pa, s);
  })();
// ]]></script>
<!--End Perfect Audience-->